name: manager_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.0.9
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  fl_chart: ^0.69.0
  collection: 1.18.0
  http_parser: ^4.0.2
  searchbar_animation: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  http_parser: ^4.1.0
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  material_color_utilities: ^0.12.0
  string_scanner: ^1.3.0
  test_api: ^0.7.3

flutter:
  uses-material-design: true

  assets:
   - Assets/Images/
   - Assets/Images/LoginAndRegister/
   - Assets/Images/HomeOwnerPanel/
   - Assets/Images/SplashScreen/
   - Assets/Images/HomeManager/
