name: owner_project_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_local_notifications: ^5.0.0+3
  shared_preferences: ^2.0.9
  flutter_svg: ^2.0.10+1
  appwrite: ^13.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - Assets/Images/
   - Assets/Images/LoginAndRegister/
   - Assets/Images/HomeOwnerPanel/

